### ISSUE TITLE
request

### ISSUE THREAD

**Issue by scavru** [bananasss00/ComfyUI-SP-Nodes#1]
Thanks for the nodes, you could make for sp_KoboldCpp a choice of instruction template. https://github.com/LostRuins/koboldcpp/tree/concedo/kcpp_adapters
models are different and they work better with their own instructions.

**Comment by bananasss00** [comment]
> Thanks for the nodes, you could make for sp_KoboldCpp a choice of instruction template. https://github.com/LostRuins/koboldcpp/tree/concedo/kcpp_adapters models are different and they work better with their own instructions.

Alright, I'll do it eventually, as I don't have too much time right now

**Comment by bananasss00** [comment]
> Thanks for the nodes, you could make for sp_KoboldCpp a choice of instruction template. https://github.com/LostRuins/koboldcpp/tree/concedo/kcpp_adapters models are different and they work better with their own instructions.

Added templates:
![image](https://github.com/user-attachments/assets/25ac85d6-dbd2-469f-9cb9-98fac80fd6e2)
